version: 2
updates:
  # Cargo dependencies
  - package-ecosystem: "cargo"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "10:00"
    open-pull-requests-limit: 10
    reviewers:
      - "Mehdi-Hp"
    assignees:
      - "Mehdi-Hp"
    commit-message:
      prefix: "deps"
      include: "scope"
    groups:
      minor-updates:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"

  # GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
      day: "monday"
      time: "10:00"
    open-pull-requests-limit: 5
    reviewers:
      - "Mehdi-Hp"
    assignees:
      - "Mehdi-Hp"
    commit-message:
      prefix: "ci"
      include: "scope"