name: Auto Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Get version from tag
        id: version
        run: |
          VERSION=${GITHUB_REF#refs/tags/v}
          echo "version=$VERSION" >> $GITHUB_OUTPUT
          echo "tag=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT
      
      - name: Generate Release Notes
        run: |
          cat > release-notes.md << 'EOF'
          ## Claude Code Personalities ${{ steps.version.outputs.version }}

          ### Installation

          #### Quick Install
          ```bash
          curl -fsSL https://raw.githubusercontent.com/Mehdi-Hp/claude-code-personalities/main/install.sh | bash
          ```

          #### Homebrew
          ```bash
          brew install Mehdi-Hp/claude-code-personalities/claude-code-personalities
          ```

          ### What's New
          See [CLAUDE.md](https://github.com/Mehdi-Hp/claude-code-personalities/blob/main/CLAUDE.md) for complete documentation.

          ### Features
          - 30+ dynamic personalities that change based on Claude's activity
          - Context-aware statusline with Nerd Font icons
          - Error state management with progressive frustration levels
          - Beautiful installer with visual progress tracking
          EOF
      
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          body_path: release-notes.md
          draft: false
          prerelease: false
          name: "${{ steps.version.outputs.tag }} - Claude Code Personalities"
      
      - name: Wait for release to be available
        run: sleep 10
      
      - name: Calculate SHA256 and Update Formula
        run: |
          # Calculate SHA256 from the release tarball
          echo "Downloading release tarball..."
          curl -sL "https://github.com/Mehdi-Hp/claude-code-personalities/archive/${{ steps.version.outputs.tag }}.tar.gz" -o release.tar.gz
          
          SHA256=$(shasum -a 256 release.tar.gz | cut -d' ' -f1)
          echo "SHA256: $SHA256"
          
          # Update formula with new SHA256 and URL
          sed -i "s/sha256 \".*\"/sha256 \"$SHA256\"/" Formula/claude-code-personalities.rb
          sed -i "s|archive/v[0-9.]*\.tar\.gz|archive/${{ steps.version.outputs.tag }}.tar.gz|" Formula/claude-code-personalities.rb
          
          # Check if there are changes to commit
          if [[ -n $(git status -s) ]]; then
            echo "Formula updated, committing changes..."
            git config user.name "github-actions[bot]"
            git config user.email "github-actions[bot]@users.noreply.github.com"
            git add Formula/claude-code-personalities.rb
            git commit -m "chore: update formula SHA256 for ${{ steps.version.outputs.tag }} [skip ci]"
            git push origin HEAD:main
          else
            echo "No formula changes needed"
          fi
      
      - name: Sync to Tap Repository
        env:
          TAP_DEPLOY_KEY: ${{ secrets.TAP_DEPLOY_KEY }}
        run: |
          # Only sync if deploy key is configured
          if [ -z "$TAP_DEPLOY_KEY" ]; then
            echo "TAP_DEPLOY_KEY not configured, skipping tap sync"
            exit 0
          fi
          
          # Setup SSH for tap repo
          mkdir -p ~/.ssh
          echo "$TAP_DEPLOY_KEY" > ~/.ssh/tap_deploy_key
          chmod 600 ~/.ssh/tap_deploy_key
          
          # Clone tap repository
          export GIT_SSH_COMMAND="ssh -i ~/.ssh/tap_deploy_key -o StrictHostKeyChecking=no"
          git clone git@personal:Mehdi-Hp/homebrew-claude-code-personalities.git tap-repo || {
            echo "Tap repository not found, skipping sync"
            exit 0
          }
          
          # Copy formula to tap repo (at root, not in Formula directory)
          cp Formula/claude-code-personalities.rb tap-repo/claude-code-personalities.rb
          
          # Commit and push if changes
          cd tap-repo
          if [[ -n $(git status -s) ]]; then
            git config user.name "github-actions[bot]"
            git config user.email "github-actions[bot]@users.noreply.github.com"
            git add claude-code-personalities.rb
            git commit -m "chore: sync formula for ${{ steps.version.outputs.tag }} release"
            git push origin main
            echo "Tap repository updated successfully"
          else
            echo "No changes needed in tap repository"
          fi
      
      - name: Post-release summary
        run: |
          echo "Release ${{ steps.version.outputs.tag }} completed!"
          echo ""
          echo "Release URL: https://github.com/Mehdi-Hp/claude-code-personalities/releases/tag/${{ steps.version.outputs.tag }}"
          echo ""
          echo "Users can install with:"
          echo "  brew install Mehdi-Hp/claude-code-personalities/claude-code-personalities"