name: Security Audit

on:
  schedule:
    # Run every Monday at 9 AM UTC
    - cron: '0 9 * * 1'
  workflow_dispatch:
  pull_request:
    paths:
      - 'Cargo.lock'
      - 'Cargo.toml'

env:
  CARGO_TERM_COLOR: always

jobs:
  security-audit:
    name: Dependency Security Audit
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
          key: ${{ runner.os }}-cargo-audit-${{ hashFiles('**/Cargo.lock') }}

      - name: Install cargo-audit
        run: cargo install cargo-audit

      - name: Run security audit
        run: cargo audit --json | tee audit-results.json

      - name: Parse audit results
        run: |
          if [ -s audit-results.json ]; then
            VULNERABILITIES=$(jq '.vulnerabilities.count' audit-results.json 2>/dev/null || echo "0")
            if [ "$VULNERABILITIES" -gt 0 ]; then
              echo "WARNING: Found $VULNERABILITIES security vulnerabilities"
              cargo audit
              exit 1
            else
              echo "SUCCESS: No security vulnerabilities found"
            fi
          else
            echo "SUCCESS: No security issues detected"
          fi

      - name: Upload audit results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: security-audit-results
          path: audit-results.json
          retention-days: 30